### ISSUE TITLE
hjt doesn't work on my mac using Homebrew

### ISSUE THREAD

**Issue by coreagile** [timqian/hacker-job-trends#1]
Did an 'npm install -g hacker-job-trends' and got the following error:

```
$ hjt 'java'
fs.js:119
    throw err;
    ^

Error: ENOENT: no such file or directory, scandir '/usr/local/lib/node_modules/hacker-job-trends/assets/rowContents'
    at Object.readdirSync (fs.js:759:3)
    at Object.<anonymous> (/usr/local/lib/node_modules/hacker-job-trends/src/index.js:42:23)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:236:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:560:3)
```

```
$ which npm
/usr/local/bin/npm

$ npm -v
6.1.0

$ node -v
v10.6.0
```

**Comment by timqian** [comment]
@coreagile Thanks for reporting this, fixed on this commit 219e4eb920a23d752b3e4b89890f163de5eca7a6

**Comment by divan** [comment]
The same. Choosing JS for writing command line tool that supposedly will be run on many computers was awful idea. The project is neat, though.

I solved this issue by cloning the repo and running `npm run getContentFromHTML`, and then copying `rowContent` to the global installation path. But before than you should install `jsom` manually. So the steps are:

```
git clone git@github.com:timqian/hacker-job-trends.git 
cd hacker-job-trends
npm install -I jsom
npm run getRowContentFromHtml
mv ./assets/rowContents /usr/local/lib/node_modules/hacker-job-trends/assets/
```

That worked for me.

```npm install -I jsom```

**Comment by timqian** [comment]
@divan it is not js’s fault, it’s my fault actually. 😅

I think you are using old version of hacker-job-trends,  try “npm upgrade -g hacker-job-trends”
