### ISSUE TITLE
Searching for 'C++' throws a SyntaxError 

### ISSUE THREAD

**Issue by sheroze1123** [timqian/hacker-job-trends#9]
Doing `hjt 'C++'` gives you this error:
```
/opt/local/lib/node_modules/hacker-job-trends/src/index.js:47
    const reg = new RegExp(matcher.keyword, 'gi');
                ^

SyntaxError: Invalid regular expression: /C++/: Nothing to repeat
    at new RegExp (<anonymous>)
    at matcherArr.map.matcher (/opt/local/lib/node_modules/hacker-job-trends/src/index.js:47:17)
    at Array.map (<anonymous>)
    at Object.<anonymous> (/opt/local/lib/node_modules/hacker-job-trends/src/index.js:46:41)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
```

The '+' in the search is probably treated as a special character in the regular expressions matcher. It probably needs to be escaped before being passed on to the regular expressions. Manually escaping them (`hjt 'C\+\+'`) seems to work fine.

**Comment by sheroze1123** [comment]
Something like this would help with escaping the keyword:
```
function escapeRegExp(str) {
  return str.replace(/[\-\[\]\/\{\}\(\)\*\+\?\.\\\^\$\|]/g, "\\$&");
}
```
Wrapping the `matcher.keyword` with this function seems to work. Code from: [https://stackoverflow.com/questions/3446170/escape-string-for-use-in-javascript-regex](https://stackoverflow.com/questions/3446170/escape-string-for-use-in-javascript-regex)
